### ISSUE TITLE
Change how changes are added.

### ISSUE THREAD

**Issue by jelmore1674** [jelmore1674/build-changelog#69]
Allow for 3 different types of changes.

## Simple array
```yaml
changed:
  - This is a change
```

## Simple flag
```yaml
changed:
  breaking:
  - This is a breaking change.
```

## Complex Object
```yaml
changed:
  - flag: breaking
    message: This is a breaking change.
    references:
    - type: issue
      number: 2
```
